# Options here can still be overridden by cmd line args.
#   sidekiq -C sidekiq.yml
---
:concurrency: 80
:pidfile: shared/tmp/pids/sidekiq.pid
:logfile: log/sidekiq.log
:queues:
  - default
  - [notifications, 40]
